import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import { NotesProvider } from "./context/NotesContext";
import { TagsProvider } from "./context/TagsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Note taking App",
  description: "Generated by Cristian Harders",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <TagsProvider>
            <Navbar></Navbar>
            <NotesProvider>{children}</NotesProvider>
          </TagsProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
